[build]
  command = "npm ci && ng build --configuration=production --prerender --output-mode=browser"
  publish = "dist/cerroautomotores-landing/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
