[build]
  command = "npm ci && ng build --configuration=production"
  publish = "dist/cerroautomotores-landing/browser"


# Fallback SPA por si luego agregás rutas de Angular
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache agresivo para assets (puede quedar así)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
